{
 "title": "Kafka-Metrics-Dashboard",
 "description": "Kafka集群Metrics数据展示",
 "tags": [ "Kafka" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(kafka_consumergroup_current_offset, job)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(kafka_consumergroup_current_offset{job=~\"$job\"}, instance)"
   },
   {
    "name": "topic",
    "label": "Topic",
    "query": "label_values(kafka_topic_partition_current_offset{instance='$instance',topic!='__consumer_offsets',topic!='--kafka'}, topic)"
   },
   {
    "name": "broker_id",
    "label": "broker_id",
    "query": "query_result(kafka_topic_partition_leader{job=\"$job\",instance=\"$instance\"})"
   }
  ]
 },
 "panels": [
  {
   "title": "Kafka集群Broker数量",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "kafka_brokers ", "legendFormat": "{{service}}" }
   ]
  },
  {
   "title": "cluster:$job Topic数量",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(kafka_topic_partitions{}) by (service)",
     "legendFormat": "$job"
    }
   ]
  },
  {
   "title": "$job $topic ISR",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_topic_partition_in_sync_replica{topic=~\"$topic\"}) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Cluster:$job Topic:$topic partitions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(topic) (kafka_topic_partitions{instance=\"$instance\",topic=~\"$topic\"})",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "broker: $broker_id partition_leader",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(kafka_topic_partition_leader{job=~\"$job\",instance=~\"$instance\",topic!=\"__consumer_offsets\"} == $broker_id) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Message in per second",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_topic_partition_current_offset{instance=\"$instance\", topic=~\"$topic\"}[1m])) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Lag by  Consumer Group",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{instance=\"$instance\",topic=~\"$topic\"}) by (consumergroup, topic) ",
     "legendFormat": "{{consumergroup}} (topic: {{topic}})"
    }
   ]
  },
  {
   "title": "Message in per minute",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(delta(kafka_topic_partition_current_offset{instance=~'$instance', topic=~\"$topic\"}[5m])/5) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Message consume per minute",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(delta(kafka_consumergroup_current_offset{instance=~'$instance',topic=~\"$topic\"}[5m])/5) by (consumergroup, topic)",
     "legendFormat": "{{consumergroup}} (topic: {{topic}})"
    }
   ]
  }
 ]
}