version: '3.5'
services:
    php8:
      build:
          context: .
          dockerfile: Dockerfile
      image: php:8.1.3-fpm
      restart: always
      privileged: true
      container_name: compose-php-8-1
      working_dir: /wwwroot
      ports:
          - "9000:9000"
      volumes:
          - ./php.ini:/usr/local/etc/php/php.ini
          - ../logs/php:/usr/local/var/log
          - ./php-fpm.d:/usr/local/etc/php-fpm.d
          - ../wwwroot:/wwwroot
          - /usr/local/var/www:/usr/share/nginx/html
          - /etc/localtime:/etc/localtime:ro
