version: '3'
services:
   nginx:
        image: nginx:stable-alpine-perl
        restart: always
        privileged: true
        container_name: nginx
        working_dir: /wwwroot
        ports:
            - "80:80"
            - "8080:8080"
            - "443:443"
        volumes:
            - ./conf.d:/etc/nginx/conf.d
            - ./fastcgi_params:/etc/nginx/fastcgi_params
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ../logs/nginx:/var/log/nginx
            - ../wwwroot:/wwwroot
            - /usr/share/nginx/html:/usr/share/nginx/html
            - /etc/localtime:/etc/localtime:ro
