version: '3.5'
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    privileged: true
    user: root
    ports:
      - 9088:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    privileged: true
    user: root
    ports:
      - 3000:3000
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
    volumes:
      - ./grafana/defaults.ini:/usr/share/grafana/conf/defaults.ini
      - ../datas/grafana:/var/lib/grafana
      - ../logs/grafana:/var/log/grafana